/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Aiekick (https://sketchfab.com/Aiekick)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/supernova-remnant-f3e97de4fdb34765b448bce71ebc0dac
Title: Supernova remnant
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import gsap from "gsap";
import { useGSAP } from "@gsap/react";
import { NoToneMapping } from "three";

const Supernova = (props) => {
  const nova = useRef();
  const { nodes, materials } = useGLTF("/models/supernova_remnant.glb");

  useGSAP(() => {
    gsap.to(nova.current.rotation, {
      y: nova.current.rotation.y + 1,
      duration: 10,
      repeat: -1,
      yoyo: true,
    });
  });
  return (
    <group {...props} dispose={null} ref={nova}>
      <group position={[0, 0.014, 0.053]}>
        <points
          geometry={nodes.Object_2.geometry}
          material={materials["Scene_-_Root"]}
        />
        <points
          geometry={nodes.Object_3.geometry}
          material={materials["Scene_-_Root"]}
        />
        <points
          geometry={nodes.Object_4.geometry}
          material={materials["Scene_-_Root"]}
        />
        <points
          geometry={nodes.Object_5.geometry}
          material={materials["Scene_-_Root"]}
        />
        <points
          geometry={nodes.Object_6.geometry}
          material={materials["Scene_-_Root"]}
        />
        <points
          geometry={nodes.Object_7.geometry}
          material={materials["Scene_-_Root"]}
        />
        <points
          geometry={nodes.Object_8.geometry}
          material={materials["Scene_-_Root"]}
        />
        <points
          geometry={nodes.Object_9.geometry}
          material={materials["Scene_-_Root"]}
        />
        <points
          geometry={nodes.Object_10.geometry}
          material={materials["Scene_-_Root"]}
        />
        <points
          geometry={nodes.Object_11.geometry}
          material={materials["Scene_-_Root"]}
        />
        <points
          geometry={nodes.Object_12.geometry}
          material={materials["Scene_-_Root"]}
        />
        <points
          geometry={nodes.Object_13.geometry}
          material={materials["Scene_-_Root"]}
        />
        <points
          geometry={nodes.Object_14.geometry}
          material={materials["Scene_-_Root"]}
        />
        <points
          geometry={nodes.Object_15.geometry}
          material={materials["Scene_-_Root"]}
        />
        <points
          geometry={nodes.Object_16.geometry}
          material={materials["Scene_-_Root"]}
        />
        <points
          geometry={nodes.Object_17.geometry}
          material={materials["Scene_-_Root"]}
        />
        <points
          geometry={nodes.Object_18.geometry}
          material={materials["Scene_-_Root"]}
        />
        <points
          geometry={nodes.Object_19.geometry}
          material={materials["Scene_-_Root"]}
        />
        <points
          geometry={nodes.Object_20.geometry}
          material={materials["Scene_-_Root"]}
        />
        <points
          geometry={nodes.Object_21.geometry}
          material={materials["Scene_-_Root"]}
        />
        <points
          geometry={nodes.Object_22.geometry}
          material={materials["Scene_-_Root"]}
        />
        <points
          geometry={nodes.Object_23.geometry}
          material={materials["Scene_-_Root"]}
        />
        <points
          geometry={nodes.Object_24.geometry}
          material={materials["Scene_-_Root"]}
        />
        <points
          geometry={nodes.Object_25.geometry}
          material={materials["Scene_-_Root"]}
        />
        <points
          geometry={nodes.Object_26.geometry}
          material={materials["Scene_-_Root"]}
        />
        <points
          geometry={nodes.Object_27.geometry}
          material={materials["Scene_-_Root"]}
        />
        <points
          geometry={nodes.Object_28.geometry}
          material={materials["Scene_-_Root"]}
        />
        <points
          geometry={nodes.Object_29.geometry}
          material={materials["Scene_-_Root"]}
        />
        <points
          geometry={nodes.Object_30.geometry}
          material={materials["Scene_-_Root"]}
        />
        <points
          geometry={nodes.Object_31.geometry}
          material={materials["Scene_-_Root"]}
        />
        <points
          geometry={nodes.Object_32.geometry}
          material={materials["Scene_-_Root"]}
        />
        <points
          geometry={nodes.Object_33.geometry}
          material={materials["Scene_-_Root"]}
        />
        <points
          geometry={nodes.Object_34.geometry}
          material={materials["Scene_-_Root"]}
        />
        <points
          geometry={nodes.Object_35.geometry}
          material={materials["Scene_-_Root"]}
        />
      </group>
    </group>
  );
};

useGLTF.preload("/models/supernova_remnant.glb");

export default Supernova;
